spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/postgres
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
    open-in-view: true
server:
  port: 8081

logging.level.org.springframework.web: INFO
logging.level.org.hibernate: INFO